In [1]:
import torch
import matplotlib.pyplot as plt

In [4]:
head_dim = 6
theta_base = 10000
context_length = 6
dtype=torch.float32

In [ ]:
inv_freq = 1.0 / (theta_base ** (2.0 * torch.arange(0, head_dim, 2, dtype=dtype)/head_dim))

# Print torch.arange(0, head_dim, 2, dtype=dtype)
print(torch.arange(0, head_dim, 2, dtype=dtype))

print("inv_freq shape:", inv_freq.shape)
print(inv_freq)

tensor([0., 2., 4.])
inv_freq shape: torch.Size([3])
tensor([1.0000, 0.0464, 0.0022])


In [6]:
positions = torch.arange(context_length, dtype=dtype)  

print("positions shape:", positions.shape)
print(positions)

positions shape: torch.Size([6])
tensor([0., 1., 2., 3., 4., 5.])
